services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy_web1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/srv/public
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php

  php:
    build: ./php
    container_name: php_web1
    volumes:
      - ./public:/srv/public
    depends_on:
      - db

  db:
    image: mariadb:10.7
    container_name: mariadb_web1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: web1
      MYSQL_USER: web1
      MYSQL_PASSWORD: web1pass123
    volumes:
      - ./data:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
